version: '3.8'

services:
#  app:
#    container_name: target-rest-api
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      PORT: 8080
#    restart: on-failure
#    volumes:
#      - .:/app
#    depends_on:
#      - db
#    links:
#      - db

  db:
    image: redis:alpine
    container_name: redis
    environment:
      - REDIS_PORT_NUMBER=6379
    ports:
      - "6379:6379"
    volumes:
      - redisDB:/data

volumes:
  redisDB:


