version: '3'
services:
  app:
    container_name: target-rest-api
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  redisDB:

